config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,  path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :user_answers, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      patch :publish, on: :member

      resources :questions do
        resources :answers
      end
    end
    resources :gists, only: %i[index]
    resources :badges
  end

  resources :contact_forms, only: %i[new create]
  resources :gists, only: %i[create]
  resources :badges, only: %i[index]

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  scope :kept, -> { where(deleted_at: nil) }

  def soft_delete
    update(deleted_at: Time.current)
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :authenticate_user!
  before_action :find_badge, only: [:edit, :update, :destroy]

  def index
    @badges = Badge.kept
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = current_user.author_badges.new(badge_params)

    if params[:badge][:image_file].present?
      # Handle file upload
      uploaded_file = params[:badge][:image_file]
      file_name = uploaded_file.original_filename
      file_path = Rails.root.join('public', 'uploads', 'badges', file_name)

      # Save file to disk
      File.open(file_path, 'wb') do |file|
        file.write(uploaded_file.read)
      end

      # Save file path to the database
      @badge.path = "/uploads/badges/#{file_name}"
    end

    if @badge.save
      redirect_to admin_badges_path, notice: 'Badge was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: 'Badge was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @badge.soft_delete
    redirect_to admin_badges_path, notice: 'Badge was successfully deleted.'
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :description, :rule_value, :path)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  before_action :authenticate_user!

  def index
    @badges = current_user.badges
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr style="text-align: center;">
  <td><%= badge.title %></td>
  <td><%= badge.description %></td>
  <td><%= badge.rule_value %></td>
  <td><%= badge.path %></td>
  <td>
    <%= link_to 'Edit', edit_admin_badge_path(badge), class: 'btn btn-warning' %>
    <%= link_to 'Delete', admin_badge_path(badge), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="card card border-primary col-md-6">
  <div class="card-body">
    <%= form_with model: [:admin, @badge] do |form| %>
      <%= render 'shared/errors', resource: @badge %>
      <div class="form-group">

        <p class="col-md-6">
          <%= form.label :title %><br>
          <%= form.text_field :title, class: 'form-control' %>
        </p>

        <p class="col-md-6">
          <%= form.label :description %><br>
          <%= form.text_field :description, class: 'form-control' %>
        </p>

        <p class="col-md-6">
          <%= form.label :rule_value %><br>
          <%= form.text_field :rule_value, class: 'form-control' %>
        </p>

        <div class="form-group">
          <%= form.label :path, "Upload Image" %><br>
          <%= form.file_field :image_file %>
        </div>

        <p> <%= form.submit class: "btn btn-outline-primary mt-3" %> </p>
      </div>
    <% end %>
  </div>
</div>

<div class="mt-2">
  <%= link_to t('nav_buttons.back'), request.referrer, class: "btn btn-primary" %>
</div>

app/views/admin/badges/edit.html.erb
<h2> Edit badge.title </h2>
<%= render 'form' %>

app/views/admin/badges/index.html.erb
<h2>All Badges</h2>

<div class="mt-2">
  <%= link_to "New badge", new_admin_badge_path, class: "btn btn-outline-primary btn-sm" %>
</div>

<div class="mt-5">
  <table class="table table-hover table-bordered ">
    <tr style="text-align: center;">
      <th><%= t('.title') %></th>
      <th><%= t('.description') %></th>
      <th><%= t('.rule_value') %></th>
      <th><%= t('.path') %></th>
    </tr>

    <%= render @badges %>
  </table>
</div>

<div class="mt-2">
  <%= link_to t('nav_buttons.back'), (request.referer || admin_tests_path), class: "btn btn-primary" %>
</div>

app/views/admin/badges/new.html.erb
<h2> Create new Badge</h2>
<%= render 'form' %>