config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,  path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :user_answers, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      patch :publish, on: :member

      resources :questions do
        resources :answers
      end
    end
    resources :gists, only: %i[index]
    resources :badges
  end

  resources :contact_forms, only: %i[new create]
  resources :gists, only: %i[create]
  resources :badges, only: %i[index]

end

app/models/question.rb
class Question < ApplicationRecord

  has_many :gists
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true

end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  scope :successful, -> { where(success: true) }

  before_validation :before_validation_set_question, on: %i[create update]

  SUCCESS_PERCENTAGE = 85

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def completed?
    current_question.nil?
  end

  def result
      correct_questions / test.questions.count.to_f * 100
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def success?
    result >= SUCCESS_PERCENTAGE
  end

  def update_success_status
    update(success: success?)
  end

  def calculate_time_left
    return 0 unless test.timer.present? && test.timer > 0

    elapsed_time = Time.current - created_at
    remaining_time = (test.timer * 60) - elapsed_time
    remaining_time > 0 ? remaining_time.to_i : 0
  end

  def expired?
    return false unless test.timer.present? && test.timer > 0
    Time.current > (created_at + test.timer.minutes)
  end

  private

  def before_validation_set_question
    if persisted?
      next_question if current_question.present?
    else
      first_question
    end
  end

  def first_question
    self.current_question = test.questions.first if test.present?
  end

  def next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answers_count
    correct_answers.count
  end

  def correct_answer?(answer_ids)
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct(true)
  end

end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user_answer, only: %i[update show result]

  def show
    @time_left_in_seconds = @user_answer.calculate_time_left
  end

  def result
  end

  def update
    @user_answer.accept!(params[:answer_ids]) unless @user_answer.expired?

    if @user_answer.completed? || @user_answer.expired?
      @user_answer.update_success_status
      new_badges = BadgeService.new(@user_answer).call if @user_answer.success?
      TestsMailer.completed_test(@user_answer).deliver_now
      redirect_to result_user_answer_path(@user_answer, badges: new_badges)
    else
      render :show
    end
  end

  private

  def set_user_answer
    @user_answer = UserAnswer.find(params[:id])
  end

end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

app/views/user_answers/result.html.erb
<h2><%= t('.header', title: @user_answer.test.title) %></h2>

<% if @user_answer.success? %>
  <div class="alert alert-success" role="alert">
    <%= t('.success', score: @user_answer.result) %>
  </div>
<% else %>
  <div class="alert alert-danger" role="alert">
    <%= t('.fail', score: @user_answer.result) %>
  </div>
<% end %>

<% if params[:badges].present? %>
  <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 50vh;">
    <div class="alert alert-success" role="alert">
      <%= "Congrats! You earned the following badges:" %>
    </div>

    <div style="display: flex; flex-wrap: wrap; gap: 20px; justify-content: center; align-items: center;">
      <% params[:badges].each do |badge_id| %>
        <% badge = Badge.find(badge_id) %>
        <div style="text-align: center;">
          <%= image_tag badge.path, width: "200", height: "200", alt: badge.title %>
          <p><%= badge.title %></p>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<%= link_to t('nav_buttons.back'), tests_path, class: 'btn btn-primary mt-3' %>

app/views/user_answers/show.html.erb
<h2> <%= t('.header', title: @user_answer.test.title) %></h2>

<div> Test progress: </div>
<p id="test-progress"></p>

<div id="timer">
  <p><%= t('time_remaining') %>: <span id="time-left" data-timeout-url="<%= result_user_answer_path(@user_answer) %>"><%= @time_left_in_seconds %></span></p>
</div>

<div> <%= t('.question') %>: </div>

<%= content_tag :p, '', class: 'question-number', data: { progress_bar: @user_answer.current_question_number } %>
<%= content_tag :p, '', class: 'questions-count', data: { progress_bar: @user_answer.test.questions.count } %>

<p>
  <b><%= @user_answer.current_question.body %></b>
</p>

<%= form_with url: user_answer_path(@user_answer), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @user_answer.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

<p>
  <%= link_to t('.gist_btn'), gists_path(id: @user_answer.id), method: :post, class: "btn btn-outline-primary btn-sm" %>
</p>

  <p><%= form.submit t('nav_buttons.next') %></p>
<% end %>