config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,  path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :user_answers, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      patch :publish, on: :member

      resources :questions do
        resources :answers
      end
    end
    resources :gists, only: %i[index]
    resources :badges
  end

  resources :contact_forms, only: %i[new create]
  resources :gists, only: %i[create]
  resources :badges, only: %i[index]

end

app/models/gist.rb
class Gist < ApplicationRecord

  belongs_to :user
  belongs_to :question

end

app/controllers/admin/gists_controller.rb
class Admin::GistsController < Admin::BaseController

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index
    @gists = Gist.all
  end

end

app/controllers/gists_controller.rb
class GistsController < ApplicationController

  before_action :set_user_answer, only: %i[create]

  def create
    service = GistQuestionService.new(@user_answer.current_question)
    result = service.call

    flash_options = if service.success?
      current_user.gists.create(
        question: @user_answer.current_question,
        gist_url: result[:html_url]
      )
      { notice: t('.success', gist_url: "#{ view_context.link_to('Gist', result[:html_url], target: "_blank").html_safe }" ) }
    else
      { alert: t('.failure') }
    end

    redirect_to @user_answer, flash_options
  end

  private

  def set_user_answer
    @user_answer = UserAnswer.find(params[:id])
  end

end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/admin/gists/_gist.html.erb
<tr style="text-align: center;">
  <td><%= link_to truncate(gist.question.body, length: 25), admin_test_question_path(gist.question.test_id, gist.question.id) %></td>
  <td><%= link_to gist.gist_url.split('/').last, gist.gist_url, target: '_blank' %></td>
  <td><%= gist.user.email %></td>
</tr>

app/views/admin/gists/index.html.erb
<h2><%= t('.header') %></h2>

<div>
  <table class="table table-hover table-bordered ">
    <tr style="text-align: center;">
      <th><%= t('.question') %></th>
      <th><%= t('.url') %></th>
      <th><%= t('.user') %></th>
    </tr>

    <%= render @gists %>
  </table>
</div>

<div class="mt-2">
  <%= link_to t('nav_buttons.back'), admin_tests_path, class: "btn btn-primary " %>
</div>